# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'todoMovies-Desafio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for todoMovies-Desafio
  pod 'Alamofire', '~> 5.2'

  target 'todoMovies-DesafioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'todoMovies-DesafioUITests' do
    # Pods for testing
  end

end
